import Sidebar from "@/components/Sidebar.jsx";

export const metadata = {
  title: "Welcome to Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="container_main">
      <Sidebar />
      {children}
    </div>
  );
}
